### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by RDKRACZ** [vanilla-friendly-datapacks/all-the-stone-tools#1]
How can I exclude/remove cobblestone from the blocks that can make stone tools?

**Comment by SirWindfield** [comment]
You can simply remove the cobblestone entry from the stone material tag file:
https://github.com/vanilla-friendly-datapacks/all-the-stone-tools/blob/master/data/minecraft/tags/items/stone_tool_materials.json

**Comment by SirWindfield** [comment]
You have to change this file:
https://github.com/vanilla-friendly-datapacks/all-the-stone-tools/blob/master/data/minecraft/tags/items/stone_tool_materials.json

```json
{
  "replace": true,
  "values": ["andesite", "diorite", "granite", "stone"]
}
```

**Comment by RDKRACZ** [comment]
Thank you
